### ISSUE TITLE
Allow the IO function to handle a promise being returned.

### ISSUE THREAD

**Issue by scull7** [influentialpublishers/jigawatt#10]
Currently the `io` function can only handle a standard JavaScript object being returned to it.  

```javascript
io: (req, data) => ({ foo: 'bar', baz: returnsPromise() })
```

I'm proposing that the following also be allowed.
```
io: (req, data) => returnsPromise()
```

**Comment by mattsmee** [comment]
sounds good to me

**Comment by scull7** [comment]
I don't know about doing this anymore, a lot of edge cases that would need to be dealt with. #11

**Comment by scull7** [comment]
Not going to implement.
