### ISSUE TITLE
Allow the `io` function to handle an array of mixed Promise and static values.

### ISSUE THREAD

**Issue by scull7** [influentialpublishers/jigawatt#11]
Currently the `io` function can only handle a standard JavaScript object being returned to it.  

```javascript
io: (req, data) => ({ foo: 'bar', baz: returnsPromise() })
```

I'm proposing that the following also be allowed.
```
io: (req, data) => [ promise1, promise2, value1, value2 ]
```

**Comment by mattsmee** [comment]
no objections

**Comment by scull7** [comment]
Doing this makes things a bit quirky.

http://goo.gl/XAZXRV
```javascript
const x = R.merge({ foo: bar }, [ 'foo' ])
// x = { foo: 'bar', "0": 'foo' }
```

I'm fairly confident that's not what the expected behavior should be.

**Comment by scull7** [comment]
Perhaps we need to make our merging smarter.  If we allow the user to return something other than a plain object then a whole host of issues arise

http://goo.gl/mJTIKz

**Comment by scull7** [comment]
Not going to implement.
